# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    - run: pnpm run build
    - uses: actions/upload-artifact@v4
      with:
        name: user-script
        path: ./dist/scu-urp-assistant.user.js
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: bookmarklet
    #     path: ./dist/scu-urp-assistant.bookmarklet.js
