# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        export PATH=$PWD/node_modules/.bin:$PATH
        npm install -g npm
        npm ci
        npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: user-script
        path: ./dist/scu-urp-assistant.user.js
    - uses: actions/upload-artifact@v4
      with:
        name: bookmarklet
        path: ./dist/scu-urp-assistant.bookmarklet.js
